[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "fd07e6efb597da6d66ee2831953335919e7c5790"
julia_version = "1.10.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "83b67014d6d26e04d8cc2a6e8960783f9287225ba23bd12a2b2e13a02dce776e"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "d243812acbcc12d630afe01909b1c7e3244e52a1"
julia_version = "1.11.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "653167d9c4085a17180370d62cec31cfadb790a3039353d9075c3eba7f06b77c"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.aarch64-apple-darwin-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "330a98930213133dda3a2277395668b94819097d"
julia_version = "1.9.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "4adb08722ef48c3dd7ec450c24c6cb0f8790d24daa2a70a4de7335870682df93"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb73f3e6a5ff76880a2100ecfbcdb499b109465d"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "9ae80c9e538344a10ae37c96a3de329303ee07869db68f78aef0367b4a38b0b3"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e545725fd3f66f49e233104791ca6e53fdb63d11"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "08a751a844b847185aa3affb8851e6cc23607c5ad0b83d7ddc6c64707a23adfd"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.aarch64-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9b373acd5e77b5a10e896313146ba8096370499"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "e217ea8c40778d0c334d342449977265da83aa7317f91ead82165b6d1f7bc777"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.aarch64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea3946086ee4e97eb593f5a54f949a858a696fb2"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "9f8a5d7e621fa06dca201c8020ea2c6de7c93b1ad5e3abd150460218d1fa40bf"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1d6eb909a4ff3da75975c6dea778e315f09a523"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "95a532b27668695fb46b1c12b60d7c876fe4690dad6bbfad0ee518bd33fe904b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.aarch64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3843b057ebd55702e13845e68d9c53ceace329c"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "9179608a1571dc67ebb64acfeea6cfc41b30ad6e717cadeca91098964dc38c26"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.aarch64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "953e5e22a7f97334afcc5e7616257043a5724da6"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "dea54725795a772847acad06f4d78251ded622c8c9bb17c870cef01415daae0b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.i686-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "253e136a6a3aa9efcaf746ad8b418fe31b5cf29c"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "7e293a0a9ebed52ba3744445749f30c1f670e8e8e81ab9e7431de31bc8ee565b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.i686-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9bd328ab7b53c4b1759754f79ec903168daf541c"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "752c9d628d16efeffeba8bbc3aaaa7676ff905330973582e1d76b0255c38ff19"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.i686-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6884e56eb00fd9f68caddf13a47985cd2bea20a6"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "6b7969570ab1b021f930e4b991994112348ee75f303acd31ac411f368c5ee164"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.i686-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27364c859482bf8377d0884112a39e76cd678c9f"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "82ca9b15dcefb3d86d29560a68fde0bc8cacfcf57d3dbd959cfbea8926356097"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.i686-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57faf07706edbeb9bd867ae3ecf9f3fce6789700"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "6810b680af98f3d436ed998a27393c81cee57e7e27a4e34b9effe4e152e36d56"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.i686-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22de6529209f94296aac1fa4cfc9864c9fd0d762"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "643462bc48ede4c4783a1f541de5d5906209058e76b7865b6edf10db49468a58"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.i686-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb948c474de24248f2b1b6896f63b49cc196f643"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "64418fda924b2f32f298d3618234e77951209bd6df43a41783628034e2efdf30"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.i686-w64-mingw32-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5cb859785abdb4753223acc3edd2c9a47cc225d"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "5e02aa1910f15f02bb422a37282db7f9a4a8ba7f543c78edb8f1b0a5b449535c"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.i686-w64-mingw32-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41cb620ab876cca50ed24d85e60277dff2909995"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "c697ee2567897ef4e476da8edc22bd215c31961dda0bc7e8fc54c546d107eaf3"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.i686-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16a5fb787217e63c6135ed1e3303a99dbdf9635c"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "a8139a9c01ebfe38c46a87c79cb59b245c2ab39972ee4736419a412d25b2a8e1"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.i686-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bbfbf4f0d5ca27a9075bb1108d3b2a332b81614"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "2e7393f056c014b0f4f5c383aa75b24c1009db0dec49a8dda052201c9864961c"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.i686-w64-mingw32-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98dabf4c669c45739174e96b9b5bcdb4c5da799f"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "7f6b5029174603da6d031825a06b92db30947b86808d769582a13963c9e143ca"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.powerpc64le-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a49137a043a81dd8bc202b59f4e99c258dfdbf1"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "b99a5a575ee7e343a14f5ab6cfefa65cd7f7b398169d1f3b936eb2224cdd9cbc"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.powerpc64le-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65283c66a9ee111620dda03de3e4147b5cb386bb"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "cc65df710bba766031e8262c6800a8481da9f25bf9c90464501fbd356015cbc4"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.powerpc64le-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5c6001ca72e6d7e7df595aed544912df9182155"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "f2eb75d640e268dc43c29946fbde2944def73f8a95c1631293eee8320c46d308"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6b555bdb17d0a33275d702d2792668d753fae8e"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "931b0b25aff9fd38052edf73cb0391b548a1739e6bbd502b87c28360f687535d"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.powerpc64le-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8db45f83716fa34e1309b67ce9513001de1366a3"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "626b00bb9003ce326761a438e716d1afbbc30168dd83df17d7a15cc32bcdd0fe"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.powerpc64le-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "d088d442d3f7683b6e43ee1bc757c5d9a82bbab3"
julia_version = "1.10.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "b4bfa833df67e31b2422e1d9494e66814e7ab3175c45a56e51a3a12dafeb39be"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "75eae472333ceeb0b3592c7b5dc771d66df548d4"
julia_version = "1.11.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "72284f115b69afa0e654eef343c153502fc5c94c46e4b2ff4208eb9936214888"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-apple-darwin-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "ac52ad43fe33fa86a634a3436922a59e28a7e919"
julia_version = "1.9.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "43f90e3fea4be62214ba89208cf9d1ed866760d5b048161e5a6fbe056401f61a"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a83e34ff41b0a269d372f642fce896624f0090b4"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "64a80d8c43a84209cc52ea40cbc3b9a18d86d5c8bf9cc6b98c32ebb26c4fa70b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c83aa3b1f5a7c84260cb10a3747fef6f21417d29"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "8b576e9f2f12969a1b5130abbfd7c5a9246c439332c600f2554ebb6b89602b1a"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "394ef230cbb14f16fc1755c09a67f056f5067ef0"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "6050086736216d091d6af7215782201cd4ba9c9744abca0fb77acee660e6cf21"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3de0aff1bf14d665115889fcf9b84a6c753edc2"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "9b95be2bf29be7f4741201f5914241057ebe56250257551799f82857bdbefeda"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16b84443525cc534d3d0fad14754340cac38ec2f"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "0d3f6fae05afd83a9c0e4ba97e70b01427647fa6059909a6d0b0bf36157a29e4"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57b3c3a2c924065789ff374fc98f9063df7724e2"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "a33b9b58b6c3aef23c73efa645547cfe9fafc3a87e32aaa8f3707278ea010fd7"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "7dc7797fa1fe467668bcc2d0a770be31344785aa"
julia_version = "1.10.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "bd4a90eab8b62c7a4fe3bbf4230253f4401c7b2a25089909c469b6b6acec50d7"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "0d1ff398448a6e7c871bcff84bfebb34585a4121"
julia_version = "1.11.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "da3235f6b84fe33ec3f45bdf2ab8f3381aaec6a2bc3188c0e97eb02d11097997"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-unknown-freebsd-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "96545c43a64c9b74b611f20a7874be548b38033a"
julia_version = "1.9.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "16c1d59f00078033e17d3d680ad7c8c8ab296f8514785515f05500484e6d035b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d6b5bb3509f856a3c6a60191248a08eb136424d"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "f181d21dc67ce7cab79f31094fc38874f543d22453f4c9289c5c4cc0c185a8dd"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4305594b8480e212bf21db16c6118562e04ae35d"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "d3080eb0f8aad4abfbc92db1f32cd60d2eb7bde5ebf8b0fc0aaf687d78aa352a"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-w64-mingw32-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4fcd0f8322939ac367c1f8d7a68f9656fa8a9149"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "4ba9f9c448e5228034fa1dcce4460dcbb2eb9b79483425c45fb2b578a2763415"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-w64-mingw32-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8397affec981361e98fdbc52cf537e5746d9b88"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "d41edd8b2dccb045d98d69e38e0d74763b867c91b899fc6868587216b24ff3c1"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7780fd1adbc500828d792955086ffde2597d8bea"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "1031dd8f60218caee476b783792dc87613f2ac2291de3d85ed90353e0afd3a02"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70eab0c1fe9760272fd28a79a77a5f58baaf8373"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "cb186d30bcdfa8ee02de03c3d1578e595b78b0892e7ccd24007621a95ed94458"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.0.0+0/ADOLC.v1.0.0.x86_64-w64-mingw32-cxx11-julia_version+1.9.0.tar.gz"
