[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "8bfbc2e810e7ad40e34352e853e2ad672abeb3e0"
julia_version = "1.10.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "ed3cbc5d97fb3c5667765084696ca865c0437805ed346e98ee5e145391b75a2e"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "6259419ce167e4f39c725565ff8a919e704decfe"
julia_version = "1.11.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "92819adc23bb24b924f654e18b129a278f13c281b5d8d9b7dad4739f0d8d987d"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.aarch64-apple-darwin-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "a54d8b4a7ca976dc3dba0d3e9b93d6ff6f9a77db"
julia_version = "1.9.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "74516ccc7d43a8fbe149c8a0143fce2515504e0fd96d24154057bada1fa9a49b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "51a39d573c932e126b9d80330e6c54c47c8be625"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "a067c3c994a4c8722011a2b4ab019899eec4f09ec2f74b8d5a9e36cbb4edc1c0"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e652e66ebf8a74eca990e53ffa18e3f917cdbfbb"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "7f0f7d0c850e7a26798a3c4094597ecf3f9229087a377cd56149779c5a875ed2"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.aarch64-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ecff478354c850509155fbb1cfa9fe48bbf0448"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "c46b140c9dbd4825c2c2b91bf40c574238bb0543e9dd69d8ac9061bb5de6d2e4"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.aarch64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "443ec9cb6e634de39bacdaaaf846410e3ffa9778"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "6e3480bb07430cf720ab0939b3469d52fc358edf0f1eea972d3fc19c8c75d714"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3e33e26bbdbeee66182e16b709ed7e20e6aaf51"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "5d1ae4f880249731da5f48bb0b0ed0e5b4f6ee5f59982de9203b6a40455f1997"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.aarch64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12e43dfe21b87e8f02f1bf1091486c7452b3a6de"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "b4b1f2a2da9844b31f7440ba3877e45e5d57410bd9763b578dab7b261e1f0140"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.aarch64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60f78e7ab7e347cb61c3db4df8842068773de4fd"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "01fbd228f21993794998485bdb728f132bffd03d0776ade2ef805ee1fdbcc6c4"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.i686-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10e545e57a40cb4563ce92ae291f6ca57de06a9a"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "79ddf12fa8b31145305199a745cea73094f4fc4d56fb840c2cbcfc7c04c208bf"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.i686-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9222e36552a8b9f73a0ab006758eca1d78ec19e0"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "1721cb43c9987a749d99954c1b2bc644150229852165ba8b70e89053867a4487"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.i686-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8db11692afdbaef19d28415f1e7c971b290d92b"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "eaca6c9dcf892370fa2867746c95ca7bf8dfa05bc83009b00a65e46156605632"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.i686-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ce1187e1e6ffd2f49f83e1d526885dfbcf539be"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "0c62a2d56b27cdd71e5a8e6aa2e2ac00326520ef66cb4e02fb0c79005a20c08f"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.i686-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a057c0cc9d77fe52e98685054545382d3774a19"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "2f6ee67be0653449c6f885148e7847b8f9e2435273705ead6b07c6a297d6b529"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.i686-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42557494f7dd2e56d4310ef9d4521327a4cdea48"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "4a48ecd8876e5087ffa9bbc6c0c30085ff59bf0532eda656736f1934ca4d300e"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.i686-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06f698671cee561e3d83625ad3910b6ca994b415"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "194ae7698e75e51a68b7152be9066ffe39d42fdacb148f9645f6cefee8e4bc6a"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.i686-w64-mingw32-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54961442330da4424eb040ab626118e489eebfbf"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "01f365fb09fac0b472bdcdea5a03f0e5caeba59f0d590446e64b98858758992b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.i686-w64-mingw32-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1af80b7be8f62bbe142916389a2d0b72a18c3720"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "d5dc85c96e63cdc65c22f6be43c96b6aa7be47de208072fb227d9e79fdc927ec"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.i686-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf86b185137ae77edbe9dac4f242941bf98dd244"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "ed12ad08fbca56005cba3f80e92f658a9512af77145fbc7187887a2ae0d6f868"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.i686-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b356ff8d01e61ef53f7d1ab39854a963cc5148d1"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "fa27850dfc6e9a3bc4a73df7f2ac065270bd8ca30a4b51ae129934f94ab9e4a2"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.i686-w64-mingw32-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6bfc8d2d4cd2af4854c321be208fffdeb52dc385"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "e105de81ad37e03f058c582a657cb1a2f64d00a55b39ff8b708141235f5934d6"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.powerpc64le-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15798a6ba445b85967996f4c210d45d3907109f7"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "f400442fe57f84442d3d49d041578e3569d852aef5be898a004d109f29847c8a"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.powerpc64le-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d078a19e442f8d0a5857d8c05a7b72ef7cf7fae4"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "01ae4c32c6657cb913b58851f9004d9ff17a8dd6621b7a45a7f921abf3445217"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.powerpc64le-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1cef0108842cc071a4ae309696529f692ddb1b2"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "e23c0823109f04991fb94e844a4cb123765e585d723a9bb978e08e95ff12f234"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "469dad5183bd6fbf6c32d7eb6eeb16eabf91e6f2"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "dba879d3cabe305a24b1c22c30a07d31f82679d8b8d76a191d46561c34733ed5"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.powerpc64le-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00039356b3daaf0c8edfd56fc3ef23bdf384c642"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "6acda08bf7e189d35b4fb1eab3cbaabf03dff5e0dcb2a91bedf49856a758deae"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.powerpc64le-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "ab104b22046a7af46d122402751f4ecd1f83138b"
julia_version = "1.10.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "4e1f7825d353c4bfa1a0697282e5de4b1a0c6f75368a2f0130cf73e5bc6a5b03"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "8dd7aa114822c0b92bfa702dab6ced2263eddb95"
julia_version = "1.11.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "a501ab85487b5e15fe71e298d6dcd72b97820fee63428a0612ce9fb37839cc10"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-apple-darwin-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "85e1a1cfa94c6f56874b8084fb9378f5768cf623"
julia_version = "1.9.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "93c9bc9e148a6ff5836346dacbee50846ffab1cd23f5cb5b387195ef702a74eb"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "742eb1db64bd995a4938c4753405dbb9bd7c0beb"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "43f4e1c18fa6be6dad1cbcd620f7220bca938d479b217a959f587b29fb751fda"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8233c1b96a3ccad0d030011e9f93d60246abce3e"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "76a692e0138c1f52b0fabba10da9b99dd852009364f5e44eb2bef2991dac0436"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4b4f138ca1ce5a96a2bf4a6d78f8d0e1a6ddd71"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "8f673ed216886f1715aa2fdaabb0b29355e488e4677a05a64c83f4e2cff8f917"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45893a01046730bdd3285b8d50d1575baeb5ed64"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "dd308b57387c9fba8fd83f8dedf88029700d4119c5407fbf54d6180d50cd5d19"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6faad261197e868aaaebcd6641f7a1c9d31d020"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "63d67af024a2dbefbc7543c2bdfbeded94182e962ae65cf63b5b9ec43fb62d46"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f26937def2c66020d852a5468ca9e26a207dea5"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "777111db32b386f66c591bca6426f472fe52db553e7a353fce84a9771c20494b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "5244b5eddb4dec0e27d550cd5e778f6a356b779f"
julia_version = "1.10.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "bd098c91ad7e01b3c3ee07957dbcf2e8e8c85c9f9c157e2443c20742b32bcb70"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "8873ac8412308ea22f0e3dd40232e05c1f6348c6"
julia_version = "1.11.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "b934e3929bed27457852b2c8c4ded327aced215ebec597ebb3d4dad6ed821f22"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-unknown-freebsd-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "58869213bd66904b360111e9802df46e6bfe3966"
julia_version = "1.9.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "c328f61b61dbd8c220b5aad33acc55270dab27efc2a8154c16d0c374b46184c1"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bbc38d4005b37234e3628055f8669930544ce932"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "54a0c8e0d64831cb70456111533842998e2b2bd836869b17ee8303828e07f6c6"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bbb202186139671f1a8e5415b99691db07ab132"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "0bf9de0731da0e36d1e2de2c1c7f60a01fbd9385d07f6506e26a29c3a6c8dbdb"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-w64-mingw32-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d988908215071262f4ea4bf2dd8d2ea243613c96"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "a6c6d885534b15da3fe60d00c6d41970adf80fc48511d5eede80571febcc75d4"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-w64-mingw32-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c34524f1d2a127c1e18c2ded734998b03d33ba19"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "4996da9183d10bf497efb821c53d2c773be4cb1ace44e6e9962a86547a2684b5"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19154427fb4283bbc495ee01bac999a3a5ba4322"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "e5a65efb1844250fae3cf82c52d463e0a6c75c88cfb387cd2c4408a1eaa458c8"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "149e219f305c896794a149440511484bb65c729f"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "57c10873fecbff59d529b96ff797bcd42b9842d858523bdcca64605204a27616"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.0+0/ADOLC.v1.1.0.x86_64-w64-mingw32-cxx11-julia_version+1.9.0.tar.gz"
