[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "591c6f78820404748f6f2f8bcaf693593f7edec7"
julia_version = "1.10.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "23970c23ce69a47c7cdc2f696573d189e210e67983dfd3c86665fbdd5f017f2e"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "ea471562da31211d69d9468dd42e77945c39e04c"
julia_version = "1.11.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "92e1f3ce948b7c48c2a6fd7b21de48826433373d63325b67edb1ad957865e469"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.aarch64-apple-darwin-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "c0195956736d5b0c6ae741850db0d3424ce5887d"
julia_version = "1.9.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "ebc33453ef96cc4d096c506be63146f2ef563531a6067518e6e62be7a886a1b4"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "854c1c139c5ef891eb667f54c3082837a2ce6566"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "33559b08d66a7ddb426fd68a869e31cca661e0b6e5eb0783f4488cdda23ee07d"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff420c2d9c55b969794a1490e0fe5bcf10e7dfe9"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "f48aa7e7c5067f2ed79bb1e9954b33ce6aa13f44de8f4823474bbb57d1b5e617"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.aarch64-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ffead21ff6791d8dd68c63f4c9510a8dec60cf0"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "3716582f5538d20a24905e4e08310cf3276af86ca399777f09b25504f1e2c6a9"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.aarch64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79a2169c3b85f0334834d62e7a9176e326206f2f"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "ef94bb7984ba5c057b854a432250446e6d5b8715440d33890526f40d9f39ca63"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8c382ea9dd8d899c6c3883ed6c53a79d9104219"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "25ebe064b5a027637ccf6fa24f49b3af5de38225522abf79aaa4b5f8e2fa5dc2"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.aarch64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5f9557308d16e9e7740bf7591b449320492166f"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "8dba489859d50480679c351fe1154eff33d40f4e29ee99ad436fc3e0d1efa5e4"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.aarch64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "669c49678907bba12b6b27fb8e7d872b010ebff4"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "684665e8ead3f00a6ba9c0d46c6e2d610e74d53928381d661f50ed38f2fab30f"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.i686-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41943b0c9cc91cf27895afa137d66a75e3e16fac"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "fd827a83f0c63598229b47b190e7a8f8109637a806da471ee242eb78a567134a"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.i686-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d2da4ed0cbb757fc2931fc78a53e3790a8921c5"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "56a636bfd00adad3646c77075325646409df6f46f8e1b95d146f692f785fe886"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.i686-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76b219a569a2c5a3b61e3f61b02bed49195d7dcc"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "8c87139285a1acf3391876aa45d335583665655f7be62b204b07b7466e35d07d"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.i686-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb091e8cd615ea3061f0f44a8315b81f76c854cf"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "346651007889aebc0f246a8340c09d9b5e4271d90e4f4499266cb63d1d311205"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.i686-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be28a60cb3b052db18e8d1bdc629a7dca87cd7d6"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "be9098ee0c63d4f61fd374c9779408831a05cdf34c81abdf6e24c1245eeda039"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.i686-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fff4a31613644cdff494c65e4d140e57b9a17857"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "12baa25bd7fcfb2294e515339973015de9ddb1dcd6056ddddc02de91f88def05"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.i686-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3dabed410a18e9e0fbd98b6d0f9c2dcd7725f00"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "8629d704c3f35c8ccb637e360a1702e5a78f91d6747811007b5de66d5ba740a5"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.i686-w64-mingw32-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a548f45cc134b0f945c7efe2f89d1bef12bf265"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "3e04d1033fadf3dfce6a2bad8eedb85c1a1464469b6258fded238fb62b95e5d6"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.i686-w64-mingw32-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c627e12e59e0e6b4fa0c8615cc751840fee9272b"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "fb6c1bb36330a96b66391166608d5bafc9c9061f3365c67ec984d4e93fbb743b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.i686-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6551f446a2207408cd9bc7b4e98e3ddde382875"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "52ea32d3708c7be0aaa95e77d4632b65f17efaa3df26d37433ea94e6762fc6fd"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.i686-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abbf412f82e6a03363301c3f0f9baabda172cffe"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "eadb3505a5c28f887355894d1e2e40a2a5a49fc9361c21d0a491d9784354367a"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.i686-w64-mingw32-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fe1cba9d34775c6eaaabd407b760c78d416cd7b"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "5437b1f56f45afecd2a6b8d8622d6a6c6a0d7179a72f08d7a6afc3596e65a754"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.powerpc64le-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "019e088479515d2197f8f0158948b55346494f4f"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "d980b0f6a2bde43a35e83c9474ad85b25fde956ffad1a41aef359d261f3cc54c"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.powerpc64le-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d8a78d38eb24cedfc02b7cbbbeb2c6a727373a4"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "8edb5760bb66ed87b413584ad4077f8d2ad9a9732ad5f67c459ca5f050a9e3b1"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.powerpc64le-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5964604e872411bc62d4f3f63effc35553543418"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "9eefe14c7ff9d9e2e04718279cedf6020d9777f34ab2094e08807b38c303e1c0"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f08ea4057b7ce374e4c4a531126394ceb07bb189"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "fb7dc8b1f24906bb64209bdedbcb88f18d4f1d6b73782bfa1a74b3a2b1a828d5"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.powerpc64le-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a70c349fb17768d5b74fd561b4b30a446639625b"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "2d67e67cdec7cfc4ad9a42493b7a721cec244e668c989e9e34bdae85c604fa8f"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.powerpc64le-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "7fbd06c891ec332370c0359e347986541d077192"
julia_version = "1.10.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "f09986b93bcc53f4f420ef9e9513c013f28b5f34c269dc599319e08957912a6f"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "ee1a51e88eeb3f83e7267c3eda3e52d7db7c7daf"
julia_version = "1.11.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "c9a0a6dfce7dc9272488b7d1aa3702e2c13e50d2b6ca35406b108442ff76fb24"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-apple-darwin-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "57d3587b20bbad95ac6ca6326cd92715288374ac"
julia_version = "1.9.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "18bf0f3424b85a6eccb7b268b9265f3fde172938b9fbcbecc0dcd762d493c338"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "345af6b6a9d465e0dc1966af22bff9086b1e225a"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "a91778e71222b1410ff31af1a82e76ef278d63bfa9c0c98293cfae94e7891826"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52a8c5a5e9d250358fbcecae0c2a7558ecbec8de"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "ded6401dc6367f424fd7f6e5e8ba633d4a2c9bbf258a002366fb90e3b5a62e3f"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13b03cdb0bd1ee6500bb8f9b02d795c95fe748b8"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "3d513c0fd30645846a903ee1198eaccaf8100f66dc1c1db52403e2745e21586f"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b145ee864b85266222a99ec3a7eb1ec52269b44b"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "a5a82996cee3f0bf8c582a2804b3f2f366eeadbb03f75c1c3effbd66b5e252de"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2cb0456da26866ff196337781f5e69e77a77d5a"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "0137766a5ace651dc14ee3ccdc54afb2e74c2a66cf46280be2c4a695daba4963"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c444f849584af4b25d2ec5189fee22c042e9f46f"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "837c7a0f3fe88e719786c3d1652621ef4ed20386fbee0a21e6a1ec8d6a8b0011"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "81e77d6e91bba75075a9690d24f95e8e60535923"
julia_version = "1.10.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "ad0c6f87e8e508f958571290dc4615b2a4117fd9ad059fe5ac32eb06bf76be33"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "17521f9909b71d114c8145f440c53f86505579e8"
julia_version = "1.11.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "f6f9cbc7bb9ccf6731384b46dfb909a29c77f03adebfbc0cef041c2707264837"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-unknown-freebsd-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "747a7c7c2f9c8290c21e6372c0b4e36c6d7d1967"
julia_version = "1.9.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "61c6e4860e88751a0bda4fbc6414c83e4356973bdda217489e2cc35243987960"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a08456d05dfe77aac3c1b8b6f15d6d33ace710b9"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "098e7d1251bad8108e1a337a2bb0eb57a934a20324b091e584b25d2085264714"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41ab0917fdb02a7dbd8ce38ef77d69ea866a15e6"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "ea2fb05f8abae70d34f0b7a590faea0de7fe875a424cc22664b704fd0c0f7e53"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-w64-mingw32-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4bbee6d5dedbaac23753bc75f2d7c2a0c65f0d37"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "bedd3bcd2e686fc43086703b1c4ff7d9fa7548f8125587384f73decd6c702303"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-w64-mingw32-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42c58411c5495c204930e2b7deed7049f6827c4a"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "bacae414fef56092a71003220d6b26b3c4aebfb7523f2e06bbe320ec9a3b7d71"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b90955b76decee53795230c90074196dd555936d"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "d238fb43c303cde2188918f36d923cc767d9511282c43cab271dc87ce7c7c8aa"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "158bcedd8252c2b5f62da681735115f9b6529c42"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "f4babd7eb7f2a913f1bb78f4b5d82451ac74ffe1d1e3e467ed1a5ca706a8ab9f"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.1+0/ADOLC.v1.1.1.x86_64-w64-mingw32-cxx11-julia_version+1.9.0.tar.gz"
