[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "e9941bb8c9c58e4c6e56fdc838445cab294c7f40"
julia_version = "1.10.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "c195e96220e4bb8be261db660aaf0b9670b22319ea41d8fdf24e35ffb3e2c928"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "8522913ce28838cae1e8cc3859624a9644801519"
julia_version = "1.11.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "9c0e808522c5bc413a9c156fec6237e6713ee88d65a7251ebd3cec351c9ef424"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.aarch64-apple-darwin-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "191532f79e03cddb2748975e6af4029b365abb51"
julia_version = "1.9.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "07556f77b0883d6d8df27722dedcb03c4327a6dd7c0526c3d1ebd4b6772f9817"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9398280789763b43b37cba1812a7bbd06aed9352"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "a0e00a85f8815b901b89117a3ce06775e4ccc1beaf25d0d80d662f92a3a60378"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fbd9e49b49d6c6b4d10967a4b40fbd9d4e755b8"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "0fd2df4929c4b645b8351edab3d70891f0315b3181461bb948a639bb820f0955"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.aarch64-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25260420e18f4d52a9379f1805a390c80578bbcf"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "5360fc3435806b991a6513110a186f5110a7d95ad8bd61b939e508671740668a"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.aarch64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3582eb75c57e283ce881b8a2fd4d90d4755f004e"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "f5e1bda14de7cc57deb08b1c9b887eecd0753f0f3592dbccf460a6f589469ed9"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9266ebf6542dd2a1bbf4b4cdbf2fb16fd7eb0fb5"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "2a0ee9bc8753c8761f3f5fc0a4ebefba36d61033b6e315ede6a987feeb8c51e0"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.aarch64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "008dcc4e6027dec684ddf87e47938c2c086411f1"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "c3bab93bbb09fb47dfdeaeb9a9fd8ccd65c1db7beb23c884396307922029ad83"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.aarch64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0c5e0a954003ae65e75ac3540de7a66a3963012"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "71171b195338fea9a364c5844a4f2cfb79f4c9e6ca0db9a3dd10f2222dbcc32c"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.i686-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70a26a6aba9d822c5a5b9fb1b5c5fac5cb373b84"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "350d19c94b85f3265ad5a951e3d859c797c1c74730b21e76dfb735ca82870fc8"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.i686-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be0a3818e4535c72ddd6c2f834e5186af28c1fa8"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "bf4f6fad176b421a37922edd9cfbabd82e0530950c60dafa234ebf57f9e5afa1"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.i686-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b934a19469342b9a49a1ad5fdaa827bf5230140"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "053d47361db1ecc69208eb483ef51b54e860e54fef98dbc8adb3fb16279df32a"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.i686-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44f89529426aa8d68be610506094b40e846df6d0"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "0b90a4d930b735527acb57180fceeb1a322aa175a1d09d9f5a655c62789b127b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.i686-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f038ac0c089e4b1f6b0d0a088d144e6ea33ba45"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "1f30f0a5ae894a343e28a5448bf073ee5dfa416b834d3acfffbc8e7268851635"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.i686-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "321409b8457e54ef4057e0d2806ecaa44da8114f"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "b8b00177ae46f52deda6b720ad295cf3871496717af236aeacf66fa05a366d42"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.i686-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb11497781350b1b50ffc0f24cb94d007fedcbc9"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "98e8f8a58414447431759f73f29f33f5ee44251ebb7b7dd6f6e11dd4fac79e0c"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.i686-w64-mingw32-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc2e4fc5dfc6c1bf029f7d831c2e2bf11660c246"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "36951b5259d0882a41fe0e760cf5356aef1eca4d2edcd3e63561a208a4a79e0c"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.i686-w64-mingw32-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0a045ffb051bf9a3ea9a422bf2c17a79f1189f3"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "63b0704e8cf09309be9d70f4628e85ba481acb0641ebeffc63ea5b6db2f7a61a"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.i686-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ec135efea7d39e4a7de7068a8b4acb7169dcd84"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "3acf08da751c7930f3c2a653a6cf8eeb19e917ae43f432038a96e870d9ebc686"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.i686-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8203c362d18f8fe4bc3b29aa7b6869dc50543e20"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "a0935ce3fb6a7d8944164ed5ec19b1e3aedbf2ef3eede09b5174017ff38a4ebe"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.i686-w64-mingw32-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "902bd709ab144ad370868f985514b9183b64d6e0"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "d27982f5bec663771480500760dad529967c69de8f49f9936a4b8eeb3d540303"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.powerpc64le-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee02443b45b42b8d2b44042c5ce6e6cc8928c634"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "f259618caa8d30cfcf49bf0960565a0196b0d3917cfbe6736bebf0cab71e9076"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.powerpc64le-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d022f9e21724c2ad9dfe3bdad0839a409605422"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "791b9dc3cb8829071f0946b2f6d0eb963b2844b78e639d733c60f79f8ac53b1d"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.powerpc64le-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0de9082affac5fbd534970719958083cf11c5cd1"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "c8cdd86b6271244613092126d14b121213e07ee749a5c84473f7cdf9bec9e563"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "176ddc25766870da378cde4e20fc84cda1f72431"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "ae5b68c834c04fa4246a5c1bae9010561e6cbfdfd7c3bcbbd8e5000f040b948d"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.powerpc64le-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c772c93c71aabf48fc109f7c15d3b9cc75a6a7da"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "ce0bac8c8df7d7cdcf6f4546639ac62de05936164d81d56586c0aff33b826784"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.powerpc64le-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "97c09f455600276b9075af1f38702fc42260bd7c"
julia_version = "1.10.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "114ee764f7222605dbd4cbc17e81fb74ef67639acae55ecd09ff7a264295ba2d"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "b25c0c46f06bfa5d1a09e13b9840defe01895931"
julia_version = "1.11.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "a95a25726de191d668163b7f11a818bafba00982810ac8ba13b2914a727c63de"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-apple-darwin-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "a44f16bef17dff7f8c69d79eea274ff34f31c877"
julia_version = "1.9.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "18afb0dfe1b9376edbfedfe9e1bbfc824eb7b9c555b0cfa9f00be2a585dacca0"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2fc91730f66b7ba5268c8bb1ace51c115e291798"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "9eeaf526cdec98e4607655c2e541911257335fe6019b45e9ac42debc79389a2e"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af67c396a634344b54213067488a1afeeec1fd4a"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "42ad9d0edb2f28931995b30228397dd57ff3ff7d21d16486f12c389d564fd248"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb562f218b37a3157e18d2ba1907d8836658d7a1"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "6a515a0b5a3b1b7d253f4f31a60a3282135dc88508fa13f3673df08f6a227726"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a06cc2b839165c5d1f7a7f5e43c60d23de70beea"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "6b66b0a180f4896e383d3a4a9dd17980c6431da9d063fb8ad725b6777e0c98ce"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1547e8ee047809e5fd0d49d59397239c34918ce5"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "b6d14febcb39f8f15b746125407cf2be0b809fa047634bba5206750772c88dde"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fbf6a3f8d384aa979a94963488db3003cea3ae8"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "a948f23c2457a415b52e0e07a7e5f39d5e799204f85ae9cf220f50f388e4c336"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "8533e7dae905d7c4204ed91e40d614ea9dd58733"
julia_version = "1.10.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "41b5e949af8d6346ec65810a0f7d07c9f95f411ecc477e8366bb80b95216ce14"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "9efb60445e9e2c8e49613ea231dfd88cdd981799"
julia_version = "1.11.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "d52d27ff898ea6edad387fb9fc06adcb3fef951452364a857f9e5edaa286a284"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-unknown-freebsd-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "8e814dcfe3668040f08bd9a728c1923544633ffa"
julia_version = "1.9.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "d7934cffe2aee8f2cebc3755ea404b8faf1ec2ef98c33852caa144ca46aae1f5"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a026a6b04caf15ac7b58d77b5326090453580631"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "d75d21ff2278ccdcc4dfb97d6f231f792d51e62e87cab2490adaca697c78e1a3"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4563d69db9306e96e429dde9fe8042647e99dc1"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "75c6bb5753cb72ec726f641d48d659f39686450549b5edc2a0919eb3aded9372"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-w64-mingw32-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d4b360b5d8458801b31184282b81769369a2d77"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "da3ea53302cc8c2cb43088056107634bc64e22ca1e904bc9f2a7f1b510478a63"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-w64-mingw32-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50dfc3e490c2f75f314724e7aeb504cc842fa014"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "a8209c1b409575840a8d51a6d7cf4dbf4614e9459cca34f5fcd8a0ce9eb48e1e"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99b361d38360d58bb7d602768d6e1d8520a782a0"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "bd8fd63e9d61de11c86d9b6f94e0537a6631b7e3b845825df7d46cf283eb1246"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e55435dae860da38e527ed11abf26bfa40da1886"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "b6be339723f4a9172dee4f0fd6ba51dbffe52511a3a8cba10197a8ea5aa6b5f5"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.1.2+0/ADOLC.v1.1.2.x86_64-w64-mingw32-cxx11-julia_version+1.9.0.tar.gz"
