[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "eb242ebd01b8ca82d8f3b39e9c864c676d6a7ee8"
os = "macos"

    [[ADOLC.download]]
    sha256 = "16cca3fedd0ba9547250c55a4cd0dd815bf9b5c42a6965baf7e15b2d5fa9b75a"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.aarch64-apple-darwin.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "a7b6c473ac6e432934c9e7adbb9732dfddc3dd28"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "0992dc7430da1874b2a259ac5df8e87bc594f6fdf3485bf52a84b49de29c532e"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.aarch64-linux-gnu.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "da11f3bea397523beb55a8a48a6ce8aba2cecb69"
libc = "musl"
os = "linux"

    [[ADOLC.download]]
    sha256 = "7348dcb949d68d0b559923a748de635b54deebd3e3129a498a327117ec6c319f"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.aarch64-linux-musl.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "6db279f56785b689daef1b336d8e7e872deb4781"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "d943c1e27b7eb947b666305205e0276e84137ef349fd24d57b2d4ef226ed8067"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.aarch64-unknown-freebsd.tar.gz"
[[ADOLC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2ef3366dbef418e810339668e46a24499f5f1b12"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "55c6ed238e245d13d5d18e8f7f020eb1be4834c0236789b0ae7a5b80a8ef4771"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.armv6l-linux-gnueabihf.tar.gz"
[[ADOLC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c9dfacb3aeb0044b0123acb1599128d801c4ec74"
libc = "musl"
os = "linux"

    [[ADOLC.download]]
    sha256 = "c5b0ebf64b94ad6a4b8a731e44ccc28661786b2439bac7229f6902abd9e6a756"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.armv6l-linux-musleabihf.tar.gz"
[[ADOLC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "035dca7addff0336e891c4ab49f621e6613b87ac"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "ffc20b2f6ce0542db5ba8f85e7b5f9d01c65550caa9531e2938b72e41798bb0b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[ADOLC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "858d46260cbaf365308ab2bd6ed810b7d212760b"
libc = "musl"
os = "linux"

    [[ADOLC.download]]
    sha256 = "8ab7182236f8cb8d7a27680f2d2cada47ae53911043fd49003669fb8fc84d5ab"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[ADOLC]]
arch = "i686"
git-tree-sha1 = "7fa09f018b7462070c32d0d5e8180af1cba7cb8b"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "b00829b35c58bdad7b363969b4c518922466497a7c8137b8e30787fbc66b51fa"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.i686-linux-gnu.tar.gz"
[[ADOLC]]
arch = "i686"
git-tree-sha1 = "64b71c1f9c832af2ab00dbd68527f02d34180525"
libc = "musl"
os = "linux"

    [[ADOLC.download]]
    sha256 = "d3bd18e54d923917ff50f336428d08128b67e382f539fab1c9106e874b163c03"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.i686-linux-musl.tar.gz"
[[ADOLC]]
arch = "i686"
git-tree-sha1 = "4910d3492a552ec73cd1536fb3285e1e90d326c8"
os = "windows"

    [[ADOLC.download]]
    sha256 = "3c6a4badf2fcdcf02f9de1f52a486cb09c030b8c1246566ef71f871d223a4d7b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.i686-w64-mingw32.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
git-tree-sha1 = "2394153aea60a1674ff2258957d8ab1da0e1a7a1"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "cec12fab4609686002a885d2e6c08518b2e7ef403e1faa8562243f835f398072"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "2ca55cb0567de41de175057c598dfa238c675663"
os = "macos"

    [[ADOLC.download]]
    sha256 = "7331af704fc934cdd0fb43963ba6e5fd66f837aee912600eb4a5107deb50de64"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.x86_64-apple-darwin.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "68a6fb07f050a661944b60194c953d3dbb351e9b"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "3e332e0b758ede1f45d9273a3f0bcc402b95d44884bb100743768097a3cb5d8f"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.x86_64-linux-gnu.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "2aee7effad97620df4f4d7d3371b78ebbe055093"
libc = "musl"
os = "linux"

    [[ADOLC.download]]
    sha256 = "6a4f1a9443c1f83449915554a76d85a980aad755ebf24fbab3991ffb0d7577d4"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.x86_64-linux-musl.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "8ae9ba4942f1c9e3802d5ceca406a8aa47e93b34"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "5c990a751ee6bebc36020349a56690045d9e1101a3fbf575cfe06518d7c049ac"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.x86_64-unknown-freebsd.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "bb29aeed7407695b76990e37beea156d3e2af7f5"
os = "windows"

    [[ADOLC.download]]
    sha256 = "eaf23331d22a543bca7d6fa7edb08fb2164bd1c75d496295b053ce7cdd376d1f"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v2.0.0+0/ADOLC.v2.0.0.x86_64-w64-mingw32.tar.gz"
