[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "3bab8020a39925ce5f65ba455eb5c4051ed8fc4d"
julia_version = "1.10.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "7c7bf2726cec31fcac5225914020477b4cca7d2aa261a6f9355fa9bacdb22f03"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "8c5c5a5e5106c5b02db9544b851539b93c70b514"
julia_version = "1.11.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "223c9ba95612bcd95b16ea3383fe4419b54f7546bdea847fe7b9918cedd5e616"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.aarch64-apple-darwin-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "da58d5ded52b909c982937bf13aa6b0cddb31100"
julia_version = "1.9.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "336e09680b751f812b9021221dd6879dceacd1e0df76a7a22a8bab2b425adaaf"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d9d6441c7fb0e2e5e27f2ea9318365a437ff2ce"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "303a010dcd7cf4172c343b329a1ac5a68e8f104cae1a32b0d24abb2def818cd7"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de2adb49567d1392de325ea306f836e593eb7106"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "56a593076fbe75cc780a965770e61b13fe6f5719c874a27933adad1db3d11af9"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.aarch64-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6339cf1075e43d85212c54e738cfeeb52ca0934b"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "996a1911511addcb5967056ec4c41a1ffb0cec430b7951d971822305e5ba8c8e"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.aarch64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65ece7dd2cd34948c67403ff012addd25fde0dce"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "ca814c2245b8792e6f1e1b5aba25f2bec602baa7dd50a735a0656ee99e8ee934"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "524dca8999dd771701affa0c38e73d4a145b9179"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "9f6e073f85e1b94fa5c86743587eef1dd82b29a25b173ae64dfe07b7d741f546"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.aarch64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e4044b82b521ed130628dda3fcd75e5efe4d6ae"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "447f096c5cc2dd0bd7b11387eabeadd76af409c3b215ec871aa4bb0f2aa54d91"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.aarch64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eac41cee31c60e76290f93f99cc962600e896218"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "d5c7a77ecbdbfdf734f77c21aafcd16bd5d8975dcf51cf5c500bd4948e30b816"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.i686-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c0ad7b126f70e8f08648f31ff00ab7393e03d6e"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "ac2f2e17dd757d711f2997f87b6aa82d5d13778894777926c2b0725769949206"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.i686-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7932f64da52e04b227ebac8198bf2069665d1fd"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "34ce8330241b986d1dc2db91df55ee372826fcbcb589ca5a18f1a3dc9f9a9c89"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.i686-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56ccaf2b5702f30f97c0b1bef26eafa2b67fcdaf"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "287cc64c9c75fede8d8e54047211f52b362b6ba09a90b0d73c8a306f09dc7ca9"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.i686-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "994fbee3dda29da354a1a8352562d7ee1b2d672b"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "32cb5e86bb70226d9f9f8e89d3fac6f89ce87c9a5d6875d455626a4282426af1"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.i686-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f0af537453e40c999bc4a06208c5eb379041d08"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "b251ee3d60fd73c03dbf19c166206e8670b1292dff9ba40faae332da6806f7b0"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.i686-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6308a305b2da1edbfc3d200c63468e2379b55cf6"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "4d5e68dce90841596bcc193ffb3d2e34d7e71dab52d752c92e35c67cdf14ad4c"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.i686-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ce81671dd8a0f757b3270fa9febac13b5dc99da"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "2394384cd3bbab8d3b9dfb32900f347f3316f4dd55adeba583dfc2b76b40d152"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.i686-w64-mingw32-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da37c45706ef527b37e750ca2008f386302a9b1a"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "398b6e77ac6eda5aa65a0b714b7e15208fc999ad62d42162117f392e977fda73"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.i686-w64-mingw32-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b9f95ada3d7b8de9b21606f3df48d18530981cd"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "6300aeff01c3350c7e23a8bbcbc0709446dcee0a98763453752a6bb75d2e150b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.i686-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24b63da452c4c1367e73245cf3c5b25d47fe5b08"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "c9365c5932b564d037be1a78a192a33f9cf050e0dfcba295f4bbf7adf85864a4"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.i686-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63b4053c7d0173a9e61a91f2bfd6754cefe640a9"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "7a34f9411842d63e9c85e40ce2bbfb95be16f07e8cb8913c31115f0de7c45a09"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.i686-w64-mingw32-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d72cffaf4123dc6314f9b61d56031e101b5644f"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "d58bccc589e7ad1cb7c52a2c5ac3329df88bad13813e3f95f29f1fb092a31e3d"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.powerpc64le-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "847fcef62d55d50d615082e61e2f94b32f66c2f7"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "5327f406783bcfb2160f6982f4ab54fb11445928ca2a1413dcec14adcaf3a934"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.powerpc64le-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df2e98a4624369483b5e92ca34b81020bcfebf67"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "828277c7192aae53a3e47f91cddd9c46e7a77c3a331bd2af4bd8f7a7cae8580e"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.powerpc64le-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c9f78cffe1d100c5524f4a1e736de8418a27588"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "57876ffc8a7dcad4ea5d4b16c128169c99339772239020f4ddbe7d00be781b85"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08cde678e6c6d5bf2e3af42d33d01371be0ae4f2"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "3f847c1240f747d0e280c5d5db5a3f53f579abe26b89999dd3132d14af8deac5"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.powerpc64le-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21d9fae92d3e289b9afb6a48236631c670d47f54"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "08b2330a91988518d73e121dc85f84e2edba3b5857b69626c75e0827270743c9"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.powerpc64le-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "3fcd9f08a1c13ba086d738b78947a136b3472813"
julia_version = "1.10.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "ec2a64c25802c67f9d274d691db692e5abd965cff95f875a133fd161edf00df4"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "f529eade2076dee3be572706d6bf6dc5b23b7b64"
julia_version = "1.11.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "6e883576982dc12c787818b03e4c4ba5325a314c83ebf83b4754b9e170f245e1"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-apple-darwin-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "0574f05b94019d4baf176f66c759422343ee8b88"
julia_version = "1.9.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "6871359bf046614b4243946e0d1b4b4146752ee4900b9698708f3633365b08ce"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d253d31edea11c28c7245f44b4d9a16b7c98a363"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "c3b88b0a15b97cb6961e03fdd66705a1c62a57c5391c2d1854c52b534e9bbb65"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b9e1207f33c080e9441d2d658a24231643f0569"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "3ef895e57f0f8449373cb7eb56f5ae10d0d9875258bdf074230120b0366033d6"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38af9ee6624845dbb29f5efc3740f4d2215311a6"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "4a076831546d9596e78e644430d196c2ec64f061c2049d1893c40c9a98701af6"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2683cde0830c32190a7deb9db4819fdf7def8a75"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "12928376a97ccf91c58accd33de0d3bc9340f8b67ac153409c91081a57b76044"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80309f9c8a941bbca670019fb8fce4ef164f2ebb"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "60aeacfd88ba46b95025fbc230776bd0b55dd0b52b2c0c1e31adf548ebbb1692"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d628a4095775363f136674c5a9695ec2c907af2"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "8039a15d046d8da9f0468dc8d06d90768c5c53f800f2111f12054763eecc37a0"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "72e233c95b4ead1d76a528fcf15fd9db9d7605cd"
julia_version = "1.10.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "934ad9a9543778979730ffb433906587a810dc91771e41f328a09f32645ad9a4"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "fc6176fac0672056c0c6bcc268ca255236b8dd72"
julia_version = "1.11.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "30ca47bd74493c7013dd0e782bc0f59e3f29f45f2ce8134253f872e9cfd3e712"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-unknown-freebsd-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "00c5189ac610f699e9443d5073d79afb116438ce"
julia_version = "1.9.0"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "00af2ea0688eb39d9988dd137fb41c0d2373d127f1de8305feb410014d474658"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4bb8c47155f223cdb5c6c6086d66084e5679bdd8"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "97ceac75f753901dfd176d8e259bc63b80c558c42b1dd7bec363778992492a8e"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1801847cb52ebac82ee61acc837eb781878fa83b"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "91715e21b366ac0af891ec7691be85babcf5a29459c86d4626271c226831422d"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-w64-mingw32-cxx03-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64a892520b3a4ceb4316096b55b4b55a1d98a9e3"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "a8e79d24d980154cae5e88410ac35d56806fc43af2a4898e0963044b71b8a455"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-w64-mingw32-cxx03-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b6d9f0fcb0499e0add4410b5ec6fea7416af0db"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "e221139cfa3a3994a9a627ab66b34e0957e91ecf1ccb6be2d1ae231a45bbe796"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b254363f12eb84823cd45092179d29486872f107"
julia_version = "1.11.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "36a26a0fa7faa12a07d672c71e7ddcc69c9a19b195a960e0e2b48891b907c57b"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "085f9747a64baaddfc132ec53474226f3f66dafc"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "ae4ab8be76950dec80ab999b6eb917841c84d3126cc2ab8093394a77b0212d12"
    url = "https://github.com/JuliaBinaryWrappers/ADOLC_jll.jl/releases/download/ADOLC-v1.2.1+0/ADOLC.v1.2.1.x86_64-w64-mingw32-cxx11-julia_version+1.9.0.tar.gz"
